#!/bin/sh
# /etc/

### BEGIN INIT INFO
# Provides:          chinachu-wui
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the chinachu-wui
# Description:       starts the chinachu-wui (USER=chinachu)
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/chinachu/chinachu/chinachu
DAEMON_OPTS="service wui execute"
NAME=chinachu-wui
USER=chinachu
PIDFILE=/var/run/${NAME}.pid

test -x $DAEMON || exit 0

start () {
  echo -n "Starting ${NAME}: "
  
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
      rm -f $PIDFILE
    else
      echo "${NAME} is already running? (pid=${PID})"
      exit
    fi
  fi
  
  PID=$(su $USER -c "exec $DAEMON $DAEMON_OPTS < /dev/null > /dev/null 2>&1 & echo \$!")
  
  if [ -z $PID ]; then
    echo "Failed!"
    exit
  else
    echo $PID > $PIDFILE
  fi
  
  echo "OK."
}

stop () {
  echo -n "Stopping ${NAME}: "
  
  PID=`cat $PIDFILE`
  if [ -f $PIDFILE ]; then
    PGID=`ps -p $PID -o pgrp | grep -v PGRP`
    kill -QUIT -`echo $PGID`
    echo "OK."
    rm -f $PIDFILE
  else
    echo "${NAME} is not running? (${PIDFILE} not found)."
  fi
}

status () {
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
      echo "${NAME} is dead but ${PIDFILE} exists."
      return 1
    else
      echo "${NAME} is running."
      return 0
    fi
  else
    echo "${NAME} is NOT running."
    return 3
  fi
}

RETVAL=0
case "$1" in
  start )
    start "$@"
    ;;
  stop )
    stop "$@"
    ;;
  restart )
    stop "$@"
    sleep 3
    start "$@"
    ;;
  status )
    status "$@"
    RETVAL=$?
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit $RETVAL

